### ISSUE TITLE
Suggested amendments

### ISSUE THREAD

**Issue by jennirpf** [raspberrypilearning/c3-wolfram-coin-and-dice#8]
Please find below a few suggestions for amendments. I have not put them in, as I have never used Wolfram and do not currently have access to it, and the suggestions are largely based on my understanding of how Wolfram operates, which may be wrong!

step 1: replace existing bullet 3 with the following: "How to use 'Dynamic' in the Wolfram Language" rather than "How to use 'Manipulate' in the Wolfram Language"

step 2: replace existing text with the following: "First, you need images of both sides of a coin. Right-click on each of these images and save them to your desktop. Drag the images from your desktop into your notebook in Wolfram. If you are using a desktop version of Wolfram, you can copy and paste the images straight from the website into your notebook."

step 4: swap the order in the following sentence: "The first row should be the `Dynamic` updated result. The second row should be the buttons you created.", so that it reads: "The first row should be the buttons you created. The second row should be the `Dynamic` updated result."

step 5: replace existing text with the following: "To make dice out of physical materials, the dice need to be designed so that when the user rolls them, they have an equal chance of landing on each side. This means that some dice cannot be made, because the number of sides that they would have do not fit a shape that could be rolled evenly. In Wolfram, this is not a problem, and you can make dice with as many sides as you like. Try making a few, like five- or seven-sided dice."

**Comment by PhilipHarney** [comment]
Thanks! I've made most of the changes, or approximations thereof!

Step 1: Changed

Step 2: Changed, but to something different, so maybe check it again. Turns out that was a slightly over-long explanation not needed right now, as we've cut the web based editor from the release versions of these projects.

Step 4: Correct! Changed!

Step 5: That is a somewhat clearer explanation alright! Fixed!

**Comment by jennirpf** [comment]
Thank you! I have had another look through and it all looks good, so I will close the ticket.
